apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-was
  template:
    metadata:
      labels:
        app: java-was
    spec:
      containers:
        - name: java-was
          image: kkmee0209/jen_tomcat:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
